spring.application.name=challenge.ceiba.funds.api

spring.devtools.restart.enabled=false
server.port=9090
spring.data.mongodb.uri=mongodb+srv://admin:Admin123*@ceiba-funds-cluster.jdbmey3.mongodb.net/ceiba_funds_db?retryWrites=true&w=majority
